public class ExceptionConverter extends java.lang.Object
{
    private final java.lang.Runnable method;

    public void <init>(java.lang.Runnable)
    {
        ExceptionConverter this;
        java.lang.Runnable method;
        sortpom.exception.ExceptionConverter $r0;

        this := @this: ExceptionConverter;

        method := @parameter0: java.lang.Runnable;

        specialinvoke this.<java.lang.Object: void <init>()>();

        $r0 = (sortpom.exception.ExceptionConverter) this;

        $r0.<sortpom.exception.ExceptionConverter: java.lang.Runnable method> = method;

        return;
    }

    public void executeAndConvertException() throws org.apache.maven.plugin.MojoFailureException
    {
        ExceptionConverter this;
        java.lang.Runnable $stack2;
        java.lang.Throwable $stack3, $stack4, $stack9, $r4, $r6;
        java.lang.String $stack6, $stack8;
        org.apache.maven.plugin.MojoFailureException $u0, $u1;
        sortpom.exception.ExceptionConverter $r0;
        sortpom.exception.FailureException $r1, $r2, $r3, $r5;

        this := @this: ExceptionConverter;

     label1:
        $r0 = (sortpom.exception.ExceptionConverter) this;

        $stack2 = $r0.<sortpom.exception.ExceptionConverter: java.lang.Runnable method>;

        interfaceinvoke $stack2.<java.lang.Runnable: void run()>();

     label2:
        goto label5;

     label3:
        $stack3 := @caughtexception;

        $r1 = (sortpom.exception.FailureException) $stack3;

        $stack4 = virtualinvoke $r1.<sortpom.exception.FailureException: java.lang.Throwable getCause()>();

        if $stack4 == null goto label4;

        $u0 = new org.apache.maven.plugin.MojoFailureException;

        $r2 = (sortpom.exception.FailureException) $stack3;

        $stack8 = virtualinvoke $r2.<sortpom.exception.FailureException: java.lang.String getMessage()>();

        $r3 = (sortpom.exception.FailureException) $stack3;

        $stack9 = virtualinvoke $r3.<sortpom.exception.FailureException: java.lang.Throwable getCause()>();

        specialinvoke $u0.<org.apache.maven.plugin.MojoFailureException: void <init>(java.lang.String,java.lang.Throwable)>($stack8, $stack9);

        $r4 = (java.lang.Throwable) $u0;

        throw $r4;

     label4:
        $u1 = new org.apache.maven.plugin.MojoFailureException;

        $r5 = (sortpom.exception.FailureException) $stack3;

        $stack6 = virtualinvoke $r5.<sortpom.exception.FailureException: java.lang.String getMessage()>();

        specialinvoke $u1.<org.apache.maven.plugin.MojoFailureException: void <init>(java.lang.String)>($stack6);

        $r6 = (java.lang.Throwable) $u1;

        throw $r6;

     label5:
        return;

        catch sortpom.exception.FailureException from label1 to label2 with label3;
    }
}
